name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./tt-rice-app
    services:
      postgres:
        image: postgres:16 
        env:
          POSTGRES_USER: prisma
          POSTGRES_PASSWORD: password
          POSTGRES_DB: testdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.17.0'

      - name: Create .env file for build process
        run: echo "${{ secrets.DOT_ENV }}" > .env

      - name: Install Dependencies
        run: npm install
      - name: Prepare temporary database
        env:
          DATABASE_URL: postgresql://prisma:password@localhost:5432/testdb
        run: |
          npx prisma migrate deploy
          npx prisma db seed
        
      - name: Build Application
        env:
          DATABASE_URL: postgresql://prisma:password@localhost:5432/testdb
          DOT_ENV_CONTENT: ${{ secrets.DOT_ENV }}
        run: |
          printf "%s" "$DOT_ENV_CONTENT" > .env
          echo "\nDATABASE_URL=${DATABASE_URL}" >> .env
          npm run build

      - name: Sync files to Droplet
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: 178.128.211.15
          REMOTE_USER: ${{ secrets.DROPLET_USER }}
          TARGET: ${{ secrets.DROPLET_APP_PATH }}
          EXCLUDE: "/.git/, /.github/, /node_modules/"

      - name: Run Post-Deployment Commands on Droplet
        uses: appleboy/ssh-action@master
        with:
          host: 178.128.211.15
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.DROPLET_APP_PATH }}
            echo "Running post-deployment commands..."
            npm install --omit=dev
            npx prisma migrate deploy
            pm2 reload my-t3-app
            pm2 save
            echo "Deployment to Droplet successful!"
